if(!require(data.table)) install.packages("data.table"); library(data.table)
if(!require(ncdf4)) install.packages("ncdf4"); library(ncdf4)
if(!require(terra)) install.packages("terra"); library(terra)
if(!require(raster)) install.packages("raster"); library(raster)
if(!require(sf)) install.packages("sf"); library(sf)
